In [1]:
import numpy as np
import pandas as pd

In [2]:
dataset = pd.read_csv(r"C:\Users\vaish\Downloads\Diabetes.csv")

In [3]:
dataset.isnull().any()

Pregnancies                 False
Glucose                     False
BloodPressure               False
SkinThickness               False
Insulin                     False
BMI                         False
DiabetesPedigreeFunction    False
Age                         False
Diabetes                    False
dtype: bool

In [4]:
dataset.head()

Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0            6      148             72             35        0  33.6   
1            8      183             64              0        0  23.3   
2            0      137             40             35      168  43.1   
3            3       78             50             32       88  31.0   
4            2      197             70             45      543  30.5   

   DiabetesPedigreeFunction  Age Diabetes  
0                     0.627   50      pos  
1                     0.672   32      pos  
2                     2.288   33      pos  
3                     0.248   26      pos  
4                     0.158   53      pos

In [5]:
dataset.isnull().any()

Pregnancies                 False
Glucose                     False
BloodPressure               False
SkinThickness               False
Insulin                     False
BMI                         False
DiabetesPedigreeFunction    False
Age                         False
Diabetes                    False
dtype: bool

In [6]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
dataset["Diabetes"] = le.fit_transform(dataset["Diabetes"])


In [7]:
dataset.head()

Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0            6      148             72             35        0  33.6   
1            8      183             64              0        0  23.3   
2            0      137             40             35      168  43.1   
3            3       78             50             32       88  31.0   
4            2      197             70             45      543  30.5   

   DiabetesPedigreeFunction  Age  Diabetes  
0                     0.627   50         1  
1                     0.672   32         1  
2                     2.288   33         1  
3                     0.248   26         1  
4                     0.158   53         1

In [8]:
x = dataset.iloc[:,0:8].values
y = dataset.iloc[:,8].values

In [9]:
x

array([[  6.   , 148.   ,  72.   , ...,  33.6  ,   0.627,  50.   ],
       [  8.   , 183.   ,  64.   , ...,  23.3  ,   0.672,  32.   ],
       [  0.   , 137.   ,  40.   , ...,  43.1  ,   2.288,  33.   ],
       ...,
       [  5.   , 121.   ,  72.   , ...,  26.2  ,   0.245,  30.   ],
       [  1.   , 126.   ,  60.   , ...,  30.1  ,   0.349,  47.   ],
       [  1.   ,  93.   ,  70.   , ...,  30.4  ,   0.315,  23.   ]])

In [10]:
y

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 0, 0, 1, 1, 1, 0, 1, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 0,
       0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 1,
       0, 0, 1, 0, 1, 1, 0, 1, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0, 0, 1, 1, 0,
       1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0,
       0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0,
       0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0,
       0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0,

In [11]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size = 0.2,random_state = 10000)

In [12]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
x_train = sc.fit_transform(x_train)
x_test = sc.fit_transform(x_test)

In [13]:
x_test

array([[-8.33643644e-01, -9.72766926e-02,  4.97499468e-01,
         1.17376044e+00, -7.68739150e-02,  8.71832595e-01,
        -5.94970806e-01, -5.19884095e-01],
       [-5.76057125e-01,  1.81058353e-01,  1.26051182e+00,
        -1.30797061e+00, -6.93379992e-01, -1.44074791e+00,
        -5.71296188e-01, -1.15529799e+00],
       [ 9.69461990e-01, -5.92094551e-01,  1.43007012e+00,
         9.82858054e-01, -6.93379992e-01,  1.47817992e+00,
        -6.69376746e-01,  1.02326393e+00],
       [-5.76057125e-01, -8.08577364e-01, -2.65512884e-01,
        -2.26190406e-01,  3.06359592e-01,  2.65485268e-01,
        -8.08042362e-01, -1.06452458e+00],
       [-3.18470606e-01,  1.04698960e+00,  1.58382867e-01,
         6.01053277e-01,  2.03924154e+00,  3.78294073e-01,
        -3.14257486e-01,  1.15529799e-01],
       [ 1.22704851e+00,  1.23254630e+00,  4.97499468e-01,
        -1.30797061e+00, -6.93379992e-01, -2.43564466e-03,
        -9.77146772e-01,  1.02326393e+00],
       [ 1.96702433e-01,  3.975411

In [14]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense

In [15]:
 ann = Sequential()

In [16]:
ann.add(Dense(8,kernel_initializer = 'random_uniform',activation = 'relu'))

In [17]:
ann.add(Dense(16,kernel_initializer = 'random_uniform',activation = 'relu'))

In [18]:
ann.add(Dense(1,kernel_initializer = 'random_uniform',activation = 'sigmoid'))

In [19]:
ann.compile('adam','binary_crossentropy',metrics = ['accuracy'])

In [20]:
ann.fit(x_train,y_train,batch_size = 32,epochs = 100)

Epoch 1/100
14/14 [==============================] - 1s 2ms/step - loss: 0.6931 - accuracy: 0.5168
Epoch 2/100
14/14 [==============================] - 0s 2ms/step - loss: 0.6929 - accuracy: 0.6000
Epoch 3/100
14/14 [==============================] - 0s 2ms/step - loss: 0.6921 - accuracy: 0.7398
Epoch 4/100
14/14 [==============================] - 0s 2ms/step - loss: 0.6899 - accuracy: 0.7537
Epoch 5/100
14/14 [==============================] - 0s 2ms/step - loss: 0.6849 - accuracy: 0.7558
Epoch 6/100
14/14 [==============================] - 0s 2ms/step - loss: 0.6761 - accuracy: 0.7376
Epoch 7/100
14/14 [==============================] - 0s 3ms/step - loss: 0.6591 - accuracy: 0.7556
Epoch 8/100
14/14 [==============================] - 0s 2ms/step - loss: 0.6384 - accuracy: 0.7720
Epoch 9/100
14/14 [==============================] - 0s 2ms/step - loss: 0.6158 - accuracy: 0.7527
Epoch 10/100
14/14 [==============================] - 0s 2ms/step - loss: 0.5983 - accuracy: 0.7484
Epoch 11/

14/14 [==============================] - 0s 2ms/step - loss: 0.5002 - accuracy: 0.7547
Epoch 84/100
14/14 [==============================] - 0s 2ms/step - loss: 0.4499 - accuracy: 0.8020
Epoch 85/100
14/14 [==============================] - 0s 2ms/step - loss: 0.4811 - accuracy: 0.7767
Epoch 86/100
14/14 [==============================] - 0s 2ms/step - loss: 0.4489 - accuracy: 0.7923
Epoch 87/100
14/14 [==============================] - 0s 2ms/step - loss: 0.4600 - accuracy: 0.7971
Epoch 88/100
14/14 [==============================] - 0s 2ms/step - loss: 0.4333 - accuracy: 0.8018
Epoch 89/100
14/14 [==============================] - 0s 2ms/step - loss: 0.4706 - accuracy: 0.7765
Epoch 90/100
14/14 [==============================] - 0s 2ms/step - loss: 0.4586 - accuracy: 0.7860
Epoch 91/100
14/14 [==============================] - 0s 2ms/step - loss: 0.4867 - accuracy: 0.7721
Epoch 92/100
14/14 [==============================] - 0s 2ms/step - loss: 0.4429 - accuracy: 0.7906
Epoch 93/100


In [21]:
yp = ann.predict(x_test)

In [22]:
yp

array([[0.52992064],
       [0.06074053],
       [0.53452146],
       [0.07413012],
       [0.910906  ],
       [0.83272886],
       [0.8871274 ],
       [0.18656027],
       [0.05312374],
       [0.9534337 ],
       [0.48859257],
       [0.56574345],
       [0.92739785],
       [0.56167525],
       [0.07074067],
       [0.3510325 ],
       [0.04718617],
       [0.24761814],
       [0.4803259 ],
       [0.31058723],
       [0.87951005],
       [0.3525781 ],
       [0.08659318],
       [0.74237067],
       [0.6368309 ],
       [0.03887692],
       [0.7708361 ],
       [0.10583633],
       [0.9560029 ],
       [0.3671842 ],
       [0.11895546],
       [0.48086452],
       [0.9726441 ],
       [0.51149285],
       [0.47091886],
       [0.90853554],
       [0.30873227],
       [0.7668388 ],
       [0.37148538],
       [0.14392415],
       [0.37113672],
       [0.10622042],
       [0.4633892 ],
       [0.08933383],
       [0.17670625],
       [0.36298338],
       [0.49124172],
       [0.436

In [23]:
yp>0.5

array([[ True],
       [False],
       [ True],
       [False],
       [ True],
       [ True],
       [ True],
       [False],
       [False],
       [ True],
       [False],
       [ True],
       [ True],
       [ True],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [ True],
       [False],
       [False],
       [ True],
       [ True],
       [False],
       [ True],
       [False],
       [ True],
       [False],
       [False],
       [False],
       [ True],
       [ True],
       [False],
       [ True],
       [False],
       [ True],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [ True],
       [False],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [False],
       [ True],
       [ True],
       [False],
       [ True],
       [ True],
       [False],
       [

In [24]:
y_test

array([0, 0, 1, 0, 1, 1, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1,
       0, 1, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0,
       0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 1,
       0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1,
       0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0, 1, 0, 0, 0, 1, 1, 0])

In [25]:
yp = ann.predict(sc.transform([[4,148,72,35,0,33.6,0.627,50]]))

In [26]:
yp

array([[0.72741705]], dtype=float32)

In [27]:
yp>0.5

array([[ True]])