In [1]:
import numpy as n
import pandas as p

In [2]:
c = p.read_csv(r"C:\Users\vaish\Downloads\50_Startups.csv")

In [3]:
c.head()

R&D Spend  Administration  Marketing Spend       State     Profit
0  165349.20       136897.80        471784.10    New York  192261.83
1  162597.70       151377.59        443898.53  California  191792.06
2  153441.51       101145.55        407934.54     Florida  191050.39
3  144372.41       118671.85        383199.62    New York  182901.99
4  142107.34        91391.77        366168.42     Florida  166187.94

In [4]:
c.isnull().any()

R&D Spend          False
Administration      True
Marketing Spend     True
State              False
Profit             False
dtype: bool

In [5]:
c["Administration"].fillna(c["Administration"].mean(),inplace=True)
c["Marketing Spend"].fillna(c["Marketing Spend"].mean(),inplace=True)

In [6]:
c.isnull().any()

R&D Spend          False
Administration     False
Marketing Spend    False
State              False
Profit             False
dtype: bool

In [7]:
x = c.iloc[:,0:4].values
y = c.iloc[:,4].values

In [8]:
x.shape

(50, 4)

In [9]:
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer
ct = ColumnTransformer([("oh",OneHotEncoder(),[3])],remainder = "passthrough")
x = ct.fit_transform(x)

In [10]:
x

array([[0.0, 0.0, 1.0, 165349.2, 136897.8, 471784.1],
       [1.0, 0.0, 0.0, 162597.7, 151377.59, 443898.53],
       [0.0, 1.0, 0.0, 153441.51, 101145.55, 407934.54],
       [0.0, 0.0, 1.0, 144372.41, 118671.85, 383199.62],
       [0.0, 1.0, 0.0, 142107.34, 91391.77, 366168.42],
       [0.0, 0.0, 1.0, 131876.9, 99814.71, 362861.36],
       [1.0, 0.0, 0.0, 134615.46, 147198.87, 212725.26673469393],
       [0.0, 1.0, 0.0, 130298.13, 145530.06, 323876.68],
       [0.0, 0.0, 1.0, 120542.52, 148718.95, 311613.29],
       [1.0, 0.0, 0.0, 123334.88, 108679.17, 304981.62],
       [0.0, 1.0, 0.0, 101913.08, 121564.03816326526, 229160.95],
       [1.0, 0.0, 0.0, 100671.96, 91790.61, 249744.55],
       [0.0, 1.0, 0.0, 93863.75, 127320.38, 249839.44],
       [1.0, 0.0, 0.0, 91992.39, 135495.07, 252664.93],
       [0.0, 1.0, 0.0, 119943.24, 156547.42, 256512.92],
       [0.0, 0.0, 1.0, 114523.61, 122616.84, 261776.23],
       [1.0, 0.0, 0.0, 78013.11, 121597.55, 264346.06],
       [0.0, 0.0, 1.0, 9

In [11]:
from sklearn.model_selection import train_test_split
xtn,xts,ytn,yts = train_test_split(x,y,test_size = 0.2,random_state=0)

In [12]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
xtn = sc.fit_transform(xtn)
xts = sc.fit_transform(xts)

In [13]:
xtn

array([[-0.81649658,  1.73205081, -0.73379939, -0.35006454, -0.78547109,
         0.08437197],
       [-0.81649658, -0.57735027,  1.36277029, -0.55530319, -1.48117426,
         0.010183  ],
       [-0.81649658,  1.73205081, -0.73379939,  0.07935762,  0.80133381,
        -0.57136866],
       [ 1.22474487, -0.57735027, -0.73379939, -0.54638238,  1.32505817,
         0.05314808],
       [-0.81649658,  1.73205081, -0.73379939,  0.43485371, -0.35598663,
         0.73767158],
       [-0.81649658,  1.73205081, -0.73379939,  1.26943143,  0.85518519,
         0.9733037 ],
       [-0.81649658,  1.73205081, -0.73379939,  1.04525007,  1.28077047,
         0.42514589],
       [-0.81649658, -0.57735027,  1.36277029, -1.529843  ,  0.02942065,
        -1.64667886],
       [-0.81649658, -0.57735027,  1.36277029, -1.53976251, -2.76767264,
        -1.66217167],
       [-0.81649658, -0.57735027,  1.36277029, -0.13115188,  1.14497701,
        -0.79035663],
       [-0.81649658, -0.57735027,  1.36277029,  0.

In [14]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense

In [15]:
ann = Sequential()

In [16]:
ann.add(Dense(6,kernel_initializer = 'random_uniform',activation = 'relu'))

In [17]:
ann.add(Dense(12,kernel_initializer = 'random_uniform',activation = 'relu'))

In [18]:
ann.add(Dense(1,kernel_initializer = 'random_uniform',activation = 'relu'))

In [19]:
ann.compile('adam','mean_squared_error',metrics = ['MSE'])

In [20]:
ann.fit(xtn,ytn,batch_size = 12,epochs = 20)

Epoch 1/20
4/4 [==============================] - 1s 3ms/step - loss: 14483890995.2000 - MSE: 14483890995.2000
Epoch 2/20
4/4 [==============================] - 0s 5ms/step - loss: 13926751436.8000 - MSE: 13926751436.8000
Epoch 3/20
4/4 [==============================] - 0s 5ms/step - loss: 13011980902.4000 - MSE: 13011980902.4000
Epoch 4/20
4/4 [==============================] - 0s 5ms/step - loss: 13461629747.2000 - MSE: 13461629747.2000
Epoch 5/20
4/4 [==============================] - 0s 3ms/step - loss: 13861215436.8000 - MSE: 13861215436.8000
Epoch 6/20
4/4 [==============================] - 0s 3ms/step - loss: 14124324249.6000 - MSE: 14124324249.6000
Epoch 7/20
4/4 [==============================] - 0s 5ms/step - loss: 12899800473.6000 - MSE: 12899800473.6000
Epoch 8/20
4/4 [==============================] - 0s 3ms/step - loss: 13159948902.4000 - MSE: 13159948902.4000
Epoch 9/20
4/4 [==============================] - 0s 3ms/step - loss: 13412893081.6000 - MSE: 13412893081.6000
E

In [21]:
yp = ann.predict(xts)

In [22]:
yp

array([[0.18186119],
       [0.240859  ],
       [0.1746442 ],
       [0.19831505],
       [0.1878419 ],
       [0.25430754],
       [0.22141773],
       [0.23009664],
       [0.17565024],
       [0.17637864]], dtype=float32)

In [23]:
yts

array([103282.38, 144259.4 , 146121.95,  77798.83, 191050.39, 105008.31,
        81229.06,  97483.56, 110352.25, 166187.94])

In [24]:
yp = ann.predict(sc.transform(ct.transform([[802387.2,891347.3,397112.1,'New York']])))

In [25]:
yp

array([[0.8023628]], dtype=float32)

In [26]:
yp>0.5

array([[ True]])