In [1]:
import numpy as n
import pandas as p

In [2]:
c = p.read_csv(r"C:\Users\vaish\Downloads\Fish.csv")

In [3]:
c.head()

Species  Weight  Length1  Length2  Length3   Height   Width
0   Bream   242.0     23.2     25.4     30.0  11.5200  4.0200
1   Bream   290.0     24.0     26.3     31.2  12.4800  4.3056
2   Bream   340.0     23.9     26.5     31.1  12.3778  4.6961
3   Bream   363.0     26.3     29.0     33.5  12.7300  4.4555
4   Bream   430.0     26.5     29.0     34.0  12.4440  5.1340

In [4]:
c.describe()

Weight     Length1     Length2     Length3      Height       Width
count   159.000000  159.000000  159.000000  159.000000  159.000000  159.000000
mean    398.326415   26.247170   28.415723   31.227044    8.970994    4.417486
std     357.978317    9.996441   10.716328   11.610246    4.286208    1.685804
min       0.000000    7.500000    8.400000    8.800000    1.728400    1.047600
25%     120.000000   19.050000   21.000000   23.150000    5.944800    3.385650
50%     273.000000   25.200000   27.300000   29.400000    7.786000    4.248500
75%     650.000000   32.700000   35.500000   39.650000   12.365900    5.584500
max    1650.000000   59.000000   63.400000   68.000000   18.957000    8.142000

In [5]:
c.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 159 entries, 0 to 158
Data columns (total 7 columns):
 #   Column   Non-Null Count  Dtype  
---  ------   --------------  -----  
 0   Species  159 non-null    object 
 1   Weight   159 non-null    float64
 2   Length1  159 non-null    float64
 3   Length2  159 non-null    float64
 4   Length3  159 non-null    float64
 5   Height   159 non-null    float64
 6   Width    159 non-null    float64
dtypes: float64(6), object(1)
memory usage: 8.8+ KB


In [6]:
c.isnull().any()

Species    False
Weight     False
Length1    False
Length2    False
Length3    False
Height     False
Width      False
dtype: bool

In [7]:
c.Species.unique()

array(['Bream', 'Roach', 'Whitefish', 'Parkki', 'Perch', 'Pike', 'Smelt'],
      dtype=object)

In [8]:
x = c.iloc[:,1:].values
y = c.iloc[:,0:1].values

In [9]:
y.shape

(159, 1)

In [10]:
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer
ct = ColumnTransformer([("oh",OneHotEncoder(),[0])],remainder = "passthrough")
y = ct.fit_transform(y).todense()

In [11]:
y.shape

(159, 7)

In [12]:
from sklearn.model_selection import train_test_split
xtn,xts,ytn,yts = train_test_split(x,y,test_size = 0.2,random_state=0)

In [13]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
xtn = sc.fit_transform(xtn)
xts = sc.fit_transform(xts)

In [14]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense

In [15]:
 ann = Sequential()

In [16]:
ann.add(Dense(6,kernel_initializer = 'random_uniform',activation = 'relu'))

In [17]:
ann.add(Dense(12,kernel_initializer = 'random_uniform',activation = 'relu'))

In [18]:
ann.add(Dense(7,kernel_initializer = 'random_uniform',activation = 'softmax'))

In [19]:
ann.compile('adam','categorical_crossentropy',metrics = ['accuracy'])

In [20]:
ann.fit(xtn,ytn,batch_size = 32,epochs = 700)

Epoch 1/700
4/4 [==============================] - 1s 6ms/step - loss: 1.9454 - accuracy: 0.2760
Epoch 2/700
4/4 [==============================] - 0s 5ms/step - loss: 1.9427 - accuracy: 0.4230
Epoch 3/700
4/4 [==============================] - 0s 5ms/step - loss: 1.9402 - accuracy: 0.3824
Epoch 4/700
4/4 [==============================] - 0s 5ms/step - loss: 1.9376 - accuracy: 0.3876
Epoch 5/700
4/4 [==============================] - 0s 3ms/step - loss: 1.9357 - accuracy: 0.3814
Epoch 6/700
4/4 [==============================] - 0s 5ms/step - loss: 1.9324 - accuracy: 0.3584
Epoch 7/700
4/4 [==============================] - 0s 4ms/step - loss: 1.9313 - accuracy: 0.3355
Epoch 8/700
4/4 [==============================] - 0s 3ms/step - loss: 1.9245 - accuracy: 0.3616
Epoch 9/700
4/4 [==============================] - 0s 5ms/step - loss: 1.9236 - accuracy: 0.3699
Epoch 10/700
4/4 [==============================] - 0s 5ms/step - loss: 1.9134 - accuracy: 0.4199
Epoch 11/700
4/4 [===========

Epoch 84/700
4/4 [==============================] - 0s 3ms/step - loss: 1.2914 - accuracy: 0.4913
Epoch 85/700
4/4 [==============================] - 0s 3ms/step - loss: 1.2198 - accuracy: 0.5475
Epoch 86/700
4/4 [==============================] - 0s 5ms/step - loss: 1.2309 - accuracy: 0.5381
Epoch 87/700
4/4 [==============================] - 0s 3ms/step - loss: 1.2592 - accuracy: 0.5173
Epoch 88/700
4/4 [==============================] - 0s 3ms/step - loss: 1.2765 - accuracy: 0.5027
Epoch 89/700
4/4 [==============================] - 0s 5ms/step - loss: 1.2505 - accuracy: 0.5131
Epoch 90/700
4/4 [==============================] - 0s 3ms/step - loss: 1.2354 - accuracy: 0.5225
Epoch 91/700
4/4 [==============================] - 0s 3ms/step - loss: 1.2494 - accuracy: 0.5163
Epoch 92/700
4/4 [==============================] - 0s 3ms/step - loss: 1.2936 - accuracy: 0.5298
Epoch 93/700
4/4 [==============================] - 0s 5ms/step - loss: 1.2123 - accuracy: 0.5455
Epoch 94/700
4/4 [==

4/4 [==============================] - 0s 5ms/step - loss: 0.9430 - accuracy: 0.6833
Epoch 167/700
4/4 [==============================] - 0s 3ms/step - loss: 0.9781 - accuracy: 0.6646
Epoch 168/700
4/4 [==============================] - 0s 3ms/step - loss: 0.8925 - accuracy: 0.7407
Epoch 169/700
4/4 [==============================] - 0s 5ms/step - loss: 0.9420 - accuracy: 0.6928
Epoch 170/700
4/4 [==============================] - 0s 3ms/step - loss: 0.9738 - accuracy: 0.6397
Epoch 171/700
4/4 [==============================] - 0s 3ms/step - loss: 0.8760 - accuracy: 0.7220
Epoch 172/700
4/4 [==============================] - 0s 3ms/step - loss: 0.9232 - accuracy: 0.7220
Epoch 173/700
4/4 [==============================] - 0s 5ms/step - loss: 0.9405 - accuracy: 0.6970
Epoch 174/700
4/4 [==============================] - 0s 3ms/step - loss: 0.8924 - accuracy: 0.7012
Epoch 175/700
4/4 [==============================] - 0s 3ms/step - loss: 0.9557 - accuracy: 0.7127
Epoch 176/700
4/4 [=====

4/4 [==============================] - 0s 0s/step - loss: 0.5580 - accuracy: 0.8244
Epoch 249/700
4/4 [==============================] - 0s 3ms/step - loss: 0.5746 - accuracy: 0.8203
Epoch 250/700
4/4 [==============================] - 0s 3ms/step - loss: 0.5634 - accuracy: 0.8161
Epoch 251/700
4/4 [==============================] - 0s 5ms/step - loss: 0.4905 - accuracy: 0.8411
Epoch 252/700
4/4 [==============================] - 0s 3ms/step - loss: 0.5507 - accuracy: 0.8088
Epoch 253/700
4/4 [==============================] - 0s 3ms/step - loss: 0.5651 - accuracy: 0.8015
Epoch 254/700
4/4 [==============================] - 0s 3ms/step - loss: 0.5177 - accuracy: 0.8276
Epoch 255/700
4/4 [==============================] - 0s 3ms/step - loss: 0.4684 - accuracy: 0.8682
Epoch 256/700
4/4 [==============================] - 0s 5ms/step - loss: 0.5801 - accuracy: 0.8067
Epoch 257/700
4/4 [==============================] - 0s 5ms/step - loss: 0.5611 - accuracy: 0.7932
Epoch 258/700
4/4 [======

4/4 [==============================] - 0s 3ms/step - loss: 0.3883 - accuracy: 0.8266
Epoch 331/700
4/4 [==============================] - 0s 3ms/step - loss: 0.4023 - accuracy: 0.8266
Epoch 332/700
4/4 [==============================] - 0s 3ms/step - loss: 0.3994 - accuracy: 0.8443
Epoch 333/700
4/4 [==============================] - 0s 5ms/step - loss: 0.3762 - accuracy: 0.8286
Epoch 334/700
4/4 [==============================] - 0s 5ms/step - loss: 0.3757 - accuracy: 0.8307
Epoch 335/700
4/4 [==============================] - 0s 3ms/step - loss: 0.4103 - accuracy: 0.8224
Epoch 336/700
4/4 [==============================] - 0s 5ms/step - loss: 0.3707 - accuracy: 0.8370
Epoch 337/700
4/4 [==============================] - 0s 3ms/step - loss: 0.4080 - accuracy: 0.8203
Epoch 338/700
4/4 [==============================] - 0s 3ms/step - loss: 0.3836 - accuracy: 0.8276
Epoch 339/700
4/4 [==============================] - 0s 3ms/step - loss: 0.3728 - accuracy: 0.8349
Epoch 340/700
4/4 [=====

4/4 [==============================] - 0s 5ms/step - loss: 0.3029 - accuracy: 0.8495
Epoch 413/700
4/4 [==============================] - 0s 5ms/step - loss: 0.3089 - accuracy: 0.8704
Epoch 414/700
4/4 [==============================] - 0s 5ms/step - loss: 0.3022 - accuracy: 0.8652
Epoch 415/700
4/4 [==============================] - 0s 5ms/step - loss: 0.3138 - accuracy: 0.8641
Epoch 416/700
4/4 [==============================] - 0s 5ms/step - loss: 0.3205 - accuracy: 0.8329
Epoch 417/700
4/4 [==============================] - 0s 5ms/step - loss: 0.3484 - accuracy: 0.8297
Epoch 418/700
4/4 [==============================] - ETA: 0s - loss: 0.3725 - accuracy: 0.84 - 0s 5ms/step - loss: 0.3239 - accuracy: 0.8589
Epoch 419/700
4/4 [==============================] - 0s 3ms/step - loss: 0.3181 - accuracy: 0.8360
Epoch 420/700
4/4 [==============================] - 0s 3ms/step - loss: 0.3296 - accuracy: 0.8360
Epoch 421/700
4/4 [==============================] - 0s 5ms/step - loss: 0.3274 -

4/4 [==============================] - 0s 3ms/step - loss: 0.2687 - accuracy: 0.8652
Epoch 494/700
4/4 [==============================] - 0s 5ms/step - loss: 0.2451 - accuracy: 0.8631
Epoch 495/700
4/4 [==============================] - 0s 5ms/step - loss: 0.2789 - accuracy: 0.8683
Epoch 496/700
4/4 [==============================] - 0s 3ms/step - loss: 0.2474 - accuracy: 0.8923
Epoch 497/700
4/4 [==============================] - 0s 3ms/step - loss: 0.2769 - accuracy: 0.8517
Epoch 498/700
4/4 [==============================] - 0s 3ms/step - loss: 0.2688 - accuracy: 0.8610
Epoch 499/700
4/4 [==============================] - 0s 5ms/step - loss: 0.2667 - accuracy: 0.8725
Epoch 500/700
4/4 [==============================] - 0s 3ms/step - loss: 0.2678 - accuracy: 0.8694
Epoch 501/700
4/4 [==============================] - 0s 3ms/step - loss: 0.2721 - accuracy: 0.8683
Epoch 502/700
4/4 [==============================] - 0s 3ms/step - loss: 0.2810 - accuracy: 0.8475
Epoch 503/700
4/4 [=====

4/4 [==============================] - 0s 3ms/step - loss: 0.2330 - accuracy: 0.8871
Epoch 575/700
4/4 [==============================] - 0s 3ms/step - loss: 0.2443 - accuracy: 0.8913
Epoch 576/700
4/4 [==============================] - 0s 3ms/step - loss: 0.2457 - accuracy: 0.8757
Epoch 577/700
4/4 [==============================] - 0s 3ms/step - loss: 0.2197 - accuracy: 0.9048
Epoch 578/700
4/4 [==============================] - 0s 3ms/step - loss: 0.2128 - accuracy: 0.8850
Epoch 579/700
4/4 [==============================] - 0s 3ms/step - loss: 0.2678 - accuracy: 0.8580
Epoch 580/700
4/4 [==============================] - 0s 3ms/step - loss: 0.2393 - accuracy: 0.8819
Epoch 581/700
4/4 [==============================] - 0s 5ms/step - loss: 0.2698 - accuracy: 0.8569
Epoch 582/700
4/4 [==============================] - 0s 3ms/step - loss: 0.2203 - accuracy: 0.9080
Epoch 583/700
4/4 [==============================] - 0s 3ms/step - loss: 0.2126 - accuracy: 0.8996
Epoch 584/700
4/4 [=====

4/4 [==============================] - 0s 3ms/step - loss: 0.2207 - accuracy: 0.9028
Epoch 657/700
4/4 [==============================] - 0s 3ms/step - loss: 0.2117 - accuracy: 0.9049
Epoch 658/700
4/4 [==============================] - 0s 3ms/step - loss: 0.2224 - accuracy: 0.8955
Epoch 659/700
4/4 [==============================] - 0s 5ms/step - loss: 0.2346 - accuracy: 0.8986
Epoch 660/700
4/4 [==============================] - 0s 3ms/step - loss: 0.2392 - accuracy: 0.8611
Epoch 661/700
4/4 [==============================] - 0s 3ms/step - loss: 0.1991 - accuracy: 0.9090
Epoch 662/700
4/4 [==============================] - 0s 5ms/step - loss: 0.1870 - accuracy: 0.9142
Epoch 663/700
4/4 [==============================] - 0s 3ms/step - loss: 0.2304 - accuracy: 0.8830
Epoch 664/700
4/4 [==============================] - 0s 5ms/step - loss: 0.2423 - accuracy: 0.8726
Epoch 665/700
4/4 [==============================] - 0s 3ms/step - loss: 0.2251 - accuracy: 0.8799
Epoch 666/700
4/4 [=====

In [21]:
yp = ann.predict(xts)

In [22]:
yp

array([[9.70298290e-01, 2.84035932e-02, 1.45886148e-08, 3.21880706e-13,
        1.23242280e-04, 1.67224729e-28, 1.17499451e-03],
       [3.62796626e-10, 5.32323169e-03, 4.96859968e-01, 1.38325229e-09,
        4.96959269e-01, 2.51841877e-04, 6.05600420e-04],
       [3.29370697e-10, 3.80999190e-05, 8.84207308e-01, 7.59914869e-08,
        1.13514274e-01, 1.79341808e-03, 4.46969789e-04],
       [5.50837171e-08, 2.63968669e-02, 2.55420953e-01, 1.21304433e-08,
        7.14386404e-01, 8.88225259e-06, 3.78687819e-03],
       [1.14356298e-02, 2.99569869e-10, 5.83481371e-01, 1.89111591e-03,
        2.17567440e-02, 9.88804756e-17, 3.81435126e-01],
       [2.61457229e-04, 2.49235395e-16, 9.08322275e-01, 2.55147868e-04,
        1.05980714e-03, 9.30799228e-24, 9.01012644e-02],
       [2.01812312e-01, 1.17140386e-09, 4.72222827e-02, 5.25110727e-06,
        2.29952820e-02, 1.34814704e-23, 7.27964878e-01],
       [1.25703892e-11, 1.32879610e-20, 6.14102304e-01, 3.85880828e-01,
        3.19539095e-06, 2

In [23]:
yp[2]

array([3.29370697e-10, 3.80999190e-05, 8.84207308e-01, 7.59914869e-08,
       1.13514274e-01, 1.79341808e-03, 4.46969789e-04], dtype=float32)

In [24]:
yts[2]

matrix([[0., 0., 1., 0., 0., 0., 0.]])

In [25]:
ann.predict(sc.transform([[700,34,36,38.3,10.6091,6.7408]]))

array([[1.4660747e-03, 7.6274089e-13, 8.2491177e-01, 1.5436416e-03,
        5.4392768e-03, 9.8309444e-19, 1.6663921e-01]], dtype=float32)

In [26]:
ann.predict_classes(sc.transform([[19.7,13.2,14.3,15.2,2.8728,2.0672]]))

C:\Users\vaish\anaconda3\lib\site-packages\tensorflow\python\keras\engine\sequential.py:450: UserWarning: `model.predict_classes()` is deprecated and will be removed after 2021-01-01. Please use instead:* `np.argmax(model.predict(x), axis=-1)`,   if your model does multi-class classification   (e.g. if it uses a `softmax` last-layer activation).* `(model.predict(x) > 0.5).astype("int32")`,   if your model does binary classification   (e.g. if it uses a `sigmoid` last-layer activation).
  warnings.warn('`model.predict_classes()` is deprecated and '


array([5], dtype=int64)